"attribute" section was mis-named "resource"
Incomplete sentence before the second example completed

The bad command with the mis-named agent has been removed:

[root@nodea ~]# pcs alert recipient add smtp-alert value=student@workstation.lab.example.com
Error: alert 'smtp-alert' does not exist